<?php

namespace Saleka\QuestionnaireBundle\Repository;

/**
 * UtilisateurQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
